### ISSUE TITLE
Web NFC support would be awesome

### ISSUE THREAD

**Issue by beaufortfrancois** [gdarchen/webusb-arduino-nfc#6]
Coming from https://twitter.com/GDarchen/status/1212796209427079168, I would love to see if Web NFC fits your needs for a fourth version of this repo.
See https://w3c.github.io/web-nfc/#examples.

**Comment by gdarchen** [comment]
Hello François !

Thanks a lot for letting me know about this project, which seems to be awesome! 👌 
I tried to activate WebNFC using the Chrome flag as described [here](https://github.com/w3c/web-nfc/issues/145#issuecomment-402735193).

However, I figured out it this flag is hidden since it tries to use an NFC Reader which is embedded in the user device. I am here using a laptop that does not embed an NFC Reader. When I tried to activate it in `chrome://flags` on my Android phone, I could find it.

The majority of people who will use my app for which I developed this device will be on laptops. Therefore, an external device seems to be the only way to ensure they can use the NFC features in all cases. 🤷‍♂ 

Once more, thanks for your proposal 🙏
